name: 'tagged-release'

on:
    push:
        tags:
            - 'v*'

jobs:
    tagged-release:
        name: 'Tagged Release'
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: run test
              run: |
                  npm ci
                  npm run test:full
                  npm run build
            - name: pack and set vars
              id: vars
              run: |
                  tagName="${GITHUB_REF#refs/*/}"
                  originalTarName="$(npm pack)"
                  # we can't rely on the npm_package_name env var here because it doesn't remove
                  # scoped package prefixes, like @toniq-labs/this-package, which then confuses
                  # the write path.
                  packageNameWithoutFileExtension="${originalTarName%.tgz}"
                  tagNameWithoutV="${tagName##v}"
                  packageName="${packageNameWithoutFileExtension%-$tagNameWithoutV}"
                  newTarName="$packageName-$tagName.tgz"
                  mv "$originalTarName" "$newTarName"
                  echo ::set-output name=tarName::"$newTarName"

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: false
                  files: |
                      ${{ steps.vars.outputs.tarName }}
